### ISSUE TITLE
`command_line` function signature doesn't match standard main

### ISSUE THREAD

**Issue by kcweicht** [Qartar/qflags#6]
The C and C++ standards both state that main should have the signature `int argc, char* argv[]`. `argv` is a non-const array to non-const strings. `qflags::command_line` takes in a `char const* const*` for argv, which works fine for passing in the command line args, but it means doing `argv = parser.remaining_argv();` doesn't work because the original `argv` is non-const, but `remaining_argv` is returning const.

**Comment by Qartar** [comment]
I don't think the use-case described here outweighs the benefits of const correctness.
